USER_PER_PAGE: 10
name:
  length:
    MAXIMUM: 50
email:
  length:
    MAXIMUM: 250
password:
  length:
    MINIMUM: 6
  expired:
    time:
      HOUR: 2
gravatar:
  user:
    SIZE: 80
  list:
    SIZE: 50
